/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fcd.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(41fcfef5ff4420a7802bb15522bc9d36)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/funcube/fcd.h>
// pydoc.h is automatically generated in the build directory
#include <fcd_pydoc.h>

void bind_fcd(py::module& m)
{

    using fcd = gr::funcube::fcd;


    py::class_<fcd, gr::block, gr::basic_block, std::shared_ptr<fcd>>(m, "fcd", D(fcd))

        .def(py::init(&fcd::make), py::arg("device_name") = "", D(fcd, make))


        ;
}
