/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fcdpp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4c4b2bc1b10843aee386290ee0f0e551)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/funcube/fcdpp.h>
// pydoc.h is automatically generated in the build directory
#include <fcdpp_pydoc.h>

void bind_fcdpp(py::module& m)
{

    using fcdpp = gr::funcube::fcdpp;


    py::class_<fcdpp, gr::block, gr::basic_block, std::shared_ptr<fcdpp>>(
        m, "fcdpp", D(fcdpp))

        .def(py::init(&fcdpp::make),
             py::arg("device_name") = "",
             py::arg("unit") = 1,
             D(fcdpp, make))


        ;
}
